services:
  #  fullstack:
  #    ports:
  #      - "8080:8080"
  #    image: abulbrr/spring-react-fullstack:v1
  postgres-db:
    image: postgres:alpine
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
volumes:
  postgres-data:
    driver: local
networks:
  default:
    external:
      name: db